# Generated by Django 5.0.6 on 2024-06-01 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor_ia', '0002_redacaocomentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacaocomentario',
            name='avaliacoes',
            field=models.ManyToManyField(null=True, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
